Music_App/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/users/activate', to: 'users#active'
  resources :users

  resource :session

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :edit, :create, :update, :destroy] do
    resources :notes, only: [:new, :create, :destroy]
  end

end

Music_App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Germania+One|Pangolin" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Germania+One" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <h1><a href="/bands">Music App</a></h1>
    <nav>
      <% if logged_in? %>
      <%= button_to 'Logout', session_url, action: 'delete', method: :delete  %>
      <% else %>
      <%= link_to "Create Account Here", new_user_url %>
      <%= link_to "Sign In", new_session_url %>
      <% end %>
    </nav>
  </header>

  <% if flash[:errors] %>
    <ul>
    <% flash[:errors].each do |error| %>
      <li> <%= error %> </li>
    <% end %>
  <% end %>

  <body>
    <%= yield %>
  </body>

</html>