Music_App/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/users/activate', to: 'users#active'
  resources :users

  resource :session

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :edit, :create, :update, :destroy] do
    resources :notes, only: [:new, :create, :destroy]
  end

end

Music_App/app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  body       :text             not null
#  user_id    :integer          not null
#  track_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Note < ApplicationRecord
  validates :user, :track, :body, presence: true
  belongs_to :user
  belongs_to :track
end

Music_App/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :ensure_logged_in

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    @note.user = current_user
    @note.track = Track.find(params[:track_id])
    if @note.save
      redirect_to track_url(@note.track)
    else
      flash.now[:errors] = @note.errors.full_messages
      render :new
    end
  end

  def destroy
    @note = Note.find(params[:track_id])
    if current_user == @note.user
      @note.destroy
      redirect_to track_url(@note.track)
    else
      flash[:errors] = { errors: @note.errors.full_messages, code: 403 }
      redirect_to track_url(@note.track)
    end
  end

  private

  def note_params
    params.require(:note).permit(:body)
  end

end

Music_App/app/views/notes/_notes.html.erb
<h4>Notes:</h4>
<%= link_to "Add A Note", new_track_note_url(track) %>

<% notes.each do |note| %>
  <h5><%= note.user.email %></h5>
  <p><%= note.body %></p>
  <% if current_user == note.user %>
    <%= button_to 'Delete', track_note_url(note), action: 'delete', method: :delete %>
  <% end %>
<% end %>

Music_App/app/views/notes/new.html.erb
<h2>Add A Note</h2>

<section class = 'form-section'>
  <form action= "<%= track_notes_url(params[:track_id]) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <textarea name="note[body]" rows="8" cols="80"></textarea><br>

    <input type="submit" value="Add A Note">
  </form>
</section>