Music_App/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/users/activate', to: 'users#active'
  resources :users

  resource :session

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :edit, :create, :update, :destroy] do
    resources :notes, only: [:new, :create, :destroy]
  end

end

Music_App/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  year       :string           not null
#  band_id    :integer          not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :title, :year, :band, presence: true
  validates_inclusion_of :live, :in => [true, false]
  belongs_to :band
  has_many :tracks,
    dependent: :destroy
end

Music_App/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :ensure_logged_in

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
    @tracks = @album.tracks
  end

  def new
    @album = Album.new
    @bands = Band.all
  end

  def create
    @album = Album.new(album_params)
    @album.live = false if params[:album][:live] == 'f'
    @bands = Band.all
    #@album.band = Band.find(params[:band_id])
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    @bands = Band.all
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    album = Album.find(params[:id])
    album.destroy
    redirect_to albums_url
  end


  private
  def album_params
    params.require(:album).permit(:title, :year, :live, :band_id)
  end

end

Music_App/app/views/albums/edit.html.erb
<h2>Edit An Album</h2>

<section class = 'form-section'>
  <form action="<%= album_url(@album) %>" method="post">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Title
      <input type="text" name="album[title]" value = '<%= @album.title %>'>
    </label>

    <label>Band
      <select name="album[band_id]">
        <% @bands.each do |band| %>
          <option value="<%= band.id %>" <%= @album.band_id == band.id ? "selected" : "" %> ><%= band.name %> </option>
        <% end %>
      </select>
    </label>

    <label>Year
      <input type="number" name="album[year]" value = '<%= @album.year %>'>
    </label>

    <label>Recorded
      <input type="radio" name="album[live]" value = "1" <%= @album.live ? 'checked' : "" %> > Live
      <input type="radio" name="album[live]"  value= '0' <%= @album.live ? '' : "checked" %> > Studio
    </label>

    <input type="submit" value="Update Album">

  </form>
</section>

Music_App/app/views/albums/index.html.erb
<h2>All Albums</h2>

<ul>
  <% @albums.each do |album| %>
    <a href='<%= album_url(album) %>'><li> <%= album.title %> | <%= album.year %> |  <%= album.band.name %> <%= album.live ? "| LIVE" : ""%></li></a>
  <% end %>
</ul>

Music_App/app/views/albums/new.html.erb
<h2>Add an album for your band</h2>

<section class = 'form-section'>
  <form action="<%= albums_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Title
      <input type="text" name="album[title]">
    </label>

    <label>Band
      <select name="album[band_id]">
        <% @bands.each do |band| %>
          <option value="<%= band.id %>" <%= band.id.to_s == params[:band_id] ? "selected" : "" %> ><%= band.name %> </option>
        <% end %>
      </select>
    </label>

    <label>Year
      <input type="number" name="album[year]" value = '2017'>
    </label>

    <label>Recorded
      <input type="radio" name="album[live]" value = "1"> Live
      <input type="radio" name="album[live]"  value= '0' checked> Studio
    </label>

    <input type="submit" value="Create Album">

  </form>
</section>

Music_App/app/views/albums/show.html.erb
<h2><%= @album.title %></h2>

<h4><%= @album.year %> |  <%= @album.band.name %> <%= @album.live ? "| LIVE" : ""%></h4>

<h4>Tracks:</h4>
<ul>
  <% @tracks.each do |track| %>
    <li><a href="<%= track_url(track) %>"><%= track.title %></a></li>
  <% end %>
</ul>

<%= link_to @album.band.name, band_url(@album.band) %> </br>
<%= link_to 'Add A Track', new_album_track_url(@album) %> </br>
<%= link_to 'Edit Album Here', edit_album_url(@album) %></br><br>
<%= button_to 'Delete Album', album_url(@album), action: 'delete', method: :delete %>