Music_App/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/users/activate', to: 'users#active'
  resources :users

  resource :session

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :edit, :create, :update, :destroy] do
    resources :notes, only: [:new, :create, :destroy]
  end

end

Music_App/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true
  has_many :albums

  has_many :tracks,
    through: :albums,
    source: :tracks
end

Music_App/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :ensure_logged_in

  def index
    @bands = Band.all
  end

  def show
    @band = Band.find(params[:id])
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.new
  end

  def update
    @band = Band.find(params[:id])
    if @band.update
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    Band.find(params[:id]).destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

Music_App/app/views/bands/edit.html.erb
<h2>Edit Your Band Here!</h2>

<section class = 'form-section'>
  <form action="/bands" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>Band Name
      <input type="text" name="band[name]" value = '<%= @band.name %>'>
    </label>

    <input type="submit" value="Edit Your Band">
  </form>
</section>

Music_App/app/views/bands/index.html.erb
<h2>Check Out All Our Bands!</h2>

<% @bands.each do |band| %>
  <h5><a href = '<%= band_url(band) %>'><%= band.name %></a></h5>
<% end %>

Music_App/app/views/bands/new.html.erb
<h2>Create A Band Here!</h2>

<section class = 'form-section'>
  <form action="/bands" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>Band Name
      <input type="text" name="band[name]">
    </label>

    <input type="submit" value="Make A Band">
  </form>
</section>

Music_App/app/views/bands/show.html.erb
<h2><%= @band.name %></h2>

<h3>Check out our albums</h3>
<ul>
  <% @band.albums.each do |album| %>
    <li><a href="<%= album_url(album) %>"><%= album.title %> |  <%= album.year %> <%= album.live ? "| LIVE" : ""%></a></li>
  <% end %>
</ul>

<%= link_to 'Add An Album For The Band', new_band_album_url(@band) %>
<%= button_to 'Delete This Band', band_url(@band), action: 'delete', method: :delete %>